version: "3.8"

services:
  backend:
    build: ./backend  # This is where your Flask app resides
    environment:
      DB_USER: speakeasy
      DB_PASSWORD: secretpassword
      DB_HOST: speakeasy_db
      DB_PORT: 5432
      DB_NAME: speakeasy_dev
    ports:
      - "5001:5001"  # Flask server running on port 5001
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: speakeasy_db
    environment:
      POSTGRES_USER: speakeasy
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: speakeasy_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata:
